### ISSUE TITLE
[Feature] Configure how often tin ore generates

### ISSUE THREAD

**Issue by accidentphilosophy** [Khazoda/bronze#16]
I absolutely love this mod, but I've found bronze very easy to acquire and produce - even more so than iron. It would be nice to see an option to configure how often tin ore spawns, to defer bronze production to slightly later in the game and make it a goal to work towards.

**Comment by Khazoda** [comment]
Using WorldEdit's //count function I found there to be about a 4:3 ratio of iron ore to tin ore (not including deepslate, where tin is rarer than iron). This is inline with my generation settings for tin compared to iron.

![image](https://github.com/user-attachments/assets/9f573168-1775-4a56-ad5a-8e3b76144c2b)
`(top count is iron ore, bottom is tin ore)`

Both ores have the same droprate of raw ore (1 piece, scaling the same with fortune).

This combined with the fact that every bronze ingot is made with 1 tin and 3 copper definitely makes bronze a little harder to get.
Maybe you've been digging at good levels for tin? The distribution with height in the world is slightly different to iron so you could just be getting lucky.

**Comment by accidentphilosophy** [comment]
I poked at it, and it looks like another mod I'm using, Lithosphere, makes tin ore spawn more often that it should.

**Comment by Khazoda** [comment]
Unfortunately Lithosphere's code is not publicly viewable and ARR so I can't check where the behaviour might be coming from, but it could just be that Lithosphere is adding its own tin generation, and because both their mod and mine add tin to fabric's common tags, they can both be used in each other's recipes.

For my mod, the worldgen is handled in the following locations:
-  `/data/bronze/worldgen/placed_feature/ore_tin.json`
-  `/data/bronze/worldgen/configured_feature/ore_tin.json`

Although I haven't tested it, it might be possible to change this with a datapack, setting values lower or to 0 etc.
If you do try this method, please let me know how it goes, I'd be interested to know :)

**Comment by accidentphilosophy** [comment]
I looked at the .jar for Lithosphere I have installed and skimmed through the files a little. I can't really understand them, but it looks like there's settings at `/data/minecraft/worldgen/noise_settings/overworld.json` (and potentially other places) dealing with ore vein generation, so that might be it?

**Comment by accidentphilosophy** [comment]
Replying again to add: Kept experimenting, and I might genuinely just be getting lucky on this world. It might also be a combination of other mods causing the issue - other modded ores throwing off the balance, maybe. I generated a new world with just Lithosphere, Bronze, and WorldEdit enabled and counted up the iron and tin ore blocks in a 64x64 block area, and the ratio was similar to your example.

**Comment by Khazoda** [comment]
Alright so I went ahead and made a quick datapack to set the amount of tin ore generating to 0, did a quick test and it's working. If you want to use this for your world feel free!

The pack is built for 1.20.1's format, but I tested it on 1.21 as well and it works. Maybe I'll include this on the mod page in future.
I'm closing this issue but if you have any questions feel free to ask :)

Datapack: [bronze_mod_remove_tin_ore.zip](https://github.com/user-attachments/files/17030644/bronze_mod_remove_tin_ore.zip)
