### ISSUE TITLE
1.21.3 update

### ISSUE THREAD

**Issue by vico93** [Khazoda/bronze#25]
Hi!

Is an update to 1.21.3 in the plans?

**Comment by Khazoda** [comment]
yes

**Comment by Khazoda** [comment]
(Basic Weapons just got updated, Bronze will be next, but it might take a couple of weeks due to personal circumstances)

**Comment by vico93** [comment]
Sorry the necroupdate, but how are things going? Would a 1.21.4 (or even a port to one of the snapshots of Spring Drop, cause the features added are so much good) update be feasible? Really miss that mod since it integrates with vanilla so perfectly!

**Comment by Khazoda** [comment]
No worries, I haven't started the bronze port yet mainly because Mojang have been shooting out new update drops constantly since 1.21 dropped. I decided to do a big functionality update for Basic Weapons instead over the last month.

As for Bronze, my current plan is to update it to 1.22 (or 1.22.1) when that releases, and keep it updated on whatever becomes the main 1.22 version (like 1.20.1, 1.21.1).

It's just so awkward keeping a bunch of mods updated when there are breaking changes from Mojang every minor update every 3 weeks or so, so I'm trying to target the major versions only. I hope you can understand :(

**Comment by Khazoda** [comment]
yes definitely, the current 1.21.4 version of Basic Storage was contributed via a PR in fact!

(Also this isn't super relevant but I will be making Bronze multiloader Fabric/NeoForge. This will be for either 1.21.1 or 1.22.x, depending on Mojang's timescale with the next major version.)
