### ISSUE TITLE
Various Bronze Block for Decorations. 

### ISSUE THREAD

**Issue by makumaku1974** [Khazoda/bronze#8]
I kinda wanted to use bronze block as a decoration block since it's much cheaper than iron and way more durable than iron. But it corrodes like copper since it is 88% copper... Yet, the distinctive thought when using bronze as a decoration block divides the usage of copper since its a weaker version for base building, or structural behaviors.

**Comment by Khazoda** [comment]
Hi, thanks for the suggestion - From the start I've been forming the bronze material's applications around a similar philosophy as iron, rather than copper (hence the weapons, tools, armour, and not many building blocks).

From what I understand you would like more types of bronze blocks to build with, similarly to how copper has many different building blocks, including grates and tiled blocks.

I'm not totally opposed to the idea, but I do want to keep bronze similar to iron and other materials that armour & weapons can be made from, meaning far fewer building blocks.

**Comment by makumaku1974** [comment]
That's what I had in mind for now. I remember some mods tend to recreate tinkers construct on how it's so diverse on creating tools and weapons. Which unfortunately nobody has succeeded till now for 1.21.

I mainly focused my mod-pack on creating a slower progression, which is why I installed Slow Your Roll mod which makes minecraft's progression really slow but rewarding in the end. Which it also integrates the Bronze with it. And still waiting for that one mod called Immersive Weathering since Iron Blocks get rusted when in contact with water or rain.

Bronze kinda hinders the use of iron tools, weapons, and armor, but it's good for competition and now useful for I guess Early Iron Golems and Rails for Minecarts.

In my opinion. I think you should create Steel to subdivide the usage with Iron, and Bronze but technically Steel is stronger than both of them. Regardless, its just an idea if you want to perhaps implement it.

**Comment by Khazoda** [comment]
Lots of cool ideas, but I'm afraid that's too far from the vision I have for the bronze mod, sorry. I don't plan on making a steel mod anytime soon either.
